name: CI on multiple JDK versions

on:
  workflow_dispatch: # No additional yaml keys are necessary
  pull_request: # No additional yaml keys are necessary
  push:
    branches:
      - "master"

jobs:
  ci-on-multiple-jdks:
    strategy:
      matrix:
        jdk_version: [8, 11]

    name: "JDK ${{ matrix.jdk_version }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: ${{ matrix.jdk_version }}
          cache: "maven"
          cache-dependency-path: |
            **/pom.xml

      - name: Print Java and Maven versions
        run: mvn --fail-fast --batch-mode --strict-checksums --version

      - name: Build, run tests, run static analysis
        run: mvn --fail-fast --batch-mode --strict-checksums clean verify

# eof
